version : '3'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  node-app:
    build: .
    image: biswajitgiri/node-app
    environment:
      - PORT=4000
    depends_on:
      - mongo
  mongo:
    image: mongo
    volumes:
      - app_data_mongo:/data/db
  redis:
    image: redis
volumes:
  app_data_mongo:
    
